content_md5: 29d45ee3f045a4d2dcff657b6fa6a1e8
filesize: 7255113
filesize_readable: 6.9 MB
meta_key: cuda_application_design_and_development
meta_relpath: paper-extra-data/pdf-meta/cuda_application_design_and_development.yaml
pdf_relpath: paper-repo/pdfs/CUDA_Application_Design_and_Development.pdf
raw_ext: .pdf
raw_filename: CUDA_Application_Design_and_Development
tags:
- other-default
- paper
- gen-from-pdf
title: Cuda Application Design And Development
url_slug: CUDA_Application_Design_and_Development
